### ISSUE TITLE
Custom root variable

### ISSUE THREAD

**Issue by Igor-Rabodzei** [qonto/ember-phone-input#105]
In this line https://github.com/qonto/ember-phone-input/blob/master/addon/services/phone-input.js#L46 we have only two states.
But I need to use custom. 
I use S3 for images and I have a problem with the flag images

**Comment by dcyriller** [comment]
I also store these flag images on S3 🤔. 

Could you provide more details? What format do you expect for the flags url? What is the format of your assets files' url? How do you deploy your app?

**Comment by dbendaou** [comment]
Closing the issue since we didn't had any news, feel free to re-open
