### ISSUE TITLE
Add separateDialCode option

### ISSUE THREAD

**Issue by AleksandrBorovkov** [qonto/ember-phone-input#122]
I have PR to add separateDialCode option, but don't have permissions to commit in this repo.

**Comment by dcyriller** [comment]
Hey @AleksandrBorovkov, thanks for trying to contribute!

Here you might find useful documentation to open a PR against this repo: https://help.github.com/en/desktop/contributing-to-projects/creating-a-pull-request

**Comment by AleksandrBorovkov** [comment]
Yes, I know the process. I mean I can't push branch with changes in this repo. 

![image](https://user-images.githubusercontent.com/22237897/65025864-2695da00-d940-11e9-9b42-f1678ad6ac2a.png)

**Comment by dcyriller** [comment]
Because you have to fork it first
