### ISSUE TITLE
50KB extra between v3.1.0 and v3.2.0

### ISSUE THREAD

**Issue by Exelord** [qonto/ember-phone-input#167]
I noticed that between v3.1.0 and v3.2.0 the build size grown up by 50KB. Is that expected?

**Comment by dcyriller** [comment]
It is not! Thanks for reporting.

I have two production apps using this package: one with the option `lazyLoad` set to true, the other with the option set to false.

I've upgraded them from `3.0.0` to `3.2.0` and checked the script that verifies the size of my bundles. The output is:
- `+231B` in vendor.js for the app with lazyLoad: false
- `+822B` in vendor.js for the app with lazyLoad: true

The issue would be specifically in v3.1.0?
