### ISSUE TITLE
Override styles

### ISSUE THREAD

**Issue by liliboxer** [qonto/ember-phone-input#232]
Is it possible to override the styles? I am not seeing any documentation on it and would love to be able to customize the look of this input. Thank you!

**Comment by rast22** [comment]
Hey!
Was the issue solved? I am trying to find exectly the same thing. I need to modify the ul color of the list dropdown.

**Comment by liliboxer** [comment]
Hey! It looks like this is the closest I got to overriding the styles. So targeting hyper specifically and matching the classes that come with the package. I don’t think there was any format follow up though 

:global(.iti) {
  // styles here
}

:global(.iti__selected-flag) {
  // styles here
}

:global(label.input) :global(.phone-input-wrapper) input::placeholder {
  // styles here
}

:global(.iti--allow-dropdown) {
  input[type='tel'] {
    // styles here
  }
}
