### ISSUE TITLE
Number in update action isn't consistent

### ISSUE THREAD

**Issue by ctjhoa** [qonto/ember-phone-input#241]
Hi,

`number` parameter in the `update` action isn't in a consistent format.
This issue is exaggerated with `separateDialCode` option enabled.

The following examples are taken from https://qonto.github.io/ember-phone-input

- With an incomplete french number -> `number` **is formatted**
![2020-07-24-123420_2355x1137_scrot](https://user-images.githubusercontent.com/1716173/88391758-50166200-cdaa-11ea-846e-ca45c4d8f2f8.png)

- With a complete french number -> `number` **is not formatted**
![2020-07-24-123433_2312x1150_scrot](https://user-images.githubusercontent.com/1716173/88391769-560c4300-cdaa-11ea-8441-935cd5c35fdf.png)

- With a french number > valid number -> `number` **is formatted**
![2020-07-24-123453_2282x1193_scrot](https://user-images.githubusercontent.com/1716173/88391780-59073380-cdaa-11ea-9859-76fddb726059.png)

You can also reproduce the issue with `separateDialCode` disabled but you have to type a number which has: length > valid number length.

I think `update` action should provide `number` in 2 versions (without formatting & with formatting).

**Comment by ctjhoa** [comment]
Looks like an issue inside [intl-tel-input](https://github.com/jackocnr/intl-tel-input).
The `getNumber` function doesn't remove formatting when number isn't valid.
eg.

With `+33 1 23 12 31 22`:
```js
 this._iti.getNumber(0) // intlTelInputUtils.numberFormat.E164
// => "+33123123122"
```

With `+33 1 23 12 31 222`:
```js
 this._iti.getNumber(0) // intlTelInputUtils.numberFormat.E164
// => "+331 23 12 31 222"
```

**Comment by dcyriller** [comment]
Thank you for investigating!
