### ISSUE TITLE
Getting Uncaught SyntaxError: Unexpected token '<' for chunk.js file

### ISSUE THREAD

**Issue by Pallavi-PH** [qonto/ember-phone-input#244]
`Uncaught SyntaxError: Unexpected token '<'` for chunk.js file. We are using `ember-cli v3.7.1` and `node 10.13.0`

![Screenshot from 2020-07-30 18-25-47](https://user-images.githubusercontent.com/34312966/88925537-4735fc80-d292-11ea-9021-6c49dc29d3fb.png)

**Comment by dcyriller** [comment]
Thanks for reporting this issue!
Could you post `chunk.5` content (maybe simplified)?
I've seen the error before when the script was not actually loaded (a 404 html page would be rendered instead).

**Comment by Pallavi-PH** [comment]
`chunk.5` loads index.html of the website.
![Screenshot from 2020-08-03 21-05-29](https://user-images.githubusercontent.com/34312966/89200051-1aa11e00-d5cd-11ea-98ef-f1e4856e91ac.png)

And this is the error.
![Screenshot from 2020-08-03 21-06-56](https://user-images.githubusercontent.com/34312966/89200295-6ce23f00-d5cd-11ea-8453-107aa9beff3d.png)

**Comment by Pallavi-PH** [comment]
Also, 404 html page was not rendered

**Comment by Pallavi-PH** [comment]
Unable to paste the complete code. It exceeds the limit provided by github

**Comment by dcyriller** [comment]
> Unable to paste the complete code. It exceeds the limit provided by github

No worries, I think I got it. Instead of the javascript bundle, `chunk.5` has an html content. The question is: why is the javascript bundle not loaded and why is the html seved instead? It could be related to the deploy pipeline. You can also try to toggle [the `lazyLoad` option](https://qonto.github.io/ember-phone-input/versions/master/docs/installation).

**Comment by Pallavi-PH** [comment]
> > Unable to paste the complete code. It exceeds the limit provided by github
> 
> No worries, I think I got it. Instead of the javascript bundle, `chunk.5` has an html content. The question is: why is the javascript bundle not loaded and why is the html served instead? It could be related to the deploy pipeline. You can also try to toggle [the `lazyLoad` option](https://qonto.github.io/ember-phone-input/versions/master/docs/installation).

I did try to toggle to `lazyload option`, the issue is still the same. Some times it renders and sometimes it doesn't

**Comment by dcyriller** [comment]
hm it's hard to tell precisely. Do you think you could reproduce the issue in a project you can share?

**Comment by Pallavi-PH** [comment]
Yes sure. You could signup here `https://account.mayadata.io` and then visit` https://portal.mayadata.io`. Then go to `Profile` --> `edit-profile`. You should be able to get the error. 
P.S. few times it loads the input field correctly. Just try to login again or refresh the page in such case

**Comment by dcyriller** [comment]
Sorry I was not clear - I would need actual code to be able to debug

**Comment by Pallavi-PH** [comment]
Sorry, It would not be possible to share the code. Can you check through source files in the debugger?
