### ISSUE TITLE
How can I get separated number and country code ?

### ISSUE THREAD

**Issue by yusufsagdic** [qonto/ember-phone-input#67]
How can I get separated number and country code ?

 +12015552103

CountryCode
` +1`
Number
`2015552103`

thanks.

**Comment by dcyriller** [comment]
For this given template:
```hbs
{{phone-input number=number update=(action "update")}}
```
the `update` function comes with two arguments: 
```javascript
update(internationalNumber, metaData) {
  this.set('number', internationalNumber);
  this.setProperties(metaData);
}
```
In the `metaData` argument, you have the `countryCode`: `metaData.selectedCountryData.dialCode`. Is it enough to infer the `number`?

**Comment by yusufsagdic** [comment]
thanks, already I'm using like this.

**Comment by dcyriller** [comment]
I'm closing it then. Feel free to reopen if needed.
