### ISSUE TITLE
Number doesn't get formatted

### ISSUE THREAD

**Issue by alejomo** [qonto/ember-phone-input#99]
I'm using ember octane, with ember-phone-input 2.0.7; when you enter a phone it doesn't get formatted, it stays visually as 3824234225 instead (382) 423-4225

**Comment by alejomo** [comment]
Nevermind it works good, looks like my update function was not set correctly and somehow was breaking the normal behavior, good work!

**Comment by dbendaou** [comment]
Glad that it finally work :)
